name: Deploy to Contabo on prod push

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /root/Food4All/deploy.sh

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 🚀 Food4All Production Deployment Complete
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          secure: true
          body: |
            ✅ Your FastAPI project has been deployed from the `prod` branch.

            Commit: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>
            Time:   ${{ github.event.head_commit.timestamp }}

            🚀 Deployed by GitHub Actions to your Contabo server.
